import { EMOJI_CATEGORIES } from './storage';

/** Palavras-chave (pt) para os emojis mais comuns — usado pela busca. */
export const EMOJI_KEYWORDS: Record<string, string[]> = {
  '🐢': ['tartaruga', 'turtle', 'devagar'],
  '🐶': ['cachorro', 'cão', 'dog', 'cao'],
  '🐱': ['gato', 'gatinho', 'cat'],
  '🐭': ['rato', 'mouse'],
  '🐹': ['hamster'],
  '🐰': ['coelho', 'rabbit', 'bunny'],
  '🦊': ['raposa', 'fox'],
  '🐻': ['urso', 'bear'],
  '🐼': ['panda'],
  '🐨': ['coala'],
  '🐯': ['tigre', 'tiger'],
  '🦁': ['leão', 'leao', 'lion'],
  '🐮': ['vaca', 'boi', 'cow'],
  '🐷': ['porco', 'pig'],
  '🐸': ['sapo', 'frog'],
  '🐵': ['macaco', 'mamaco', 'monkey'],
  '🙈': ['macaco', 'mamaco', 'sem ver'],
  '🙉': ['macaco', 'mamaco', 'sem ouvir'],
  '🙊': ['macaco', 'mamaco', 'sem falar'],
  '🐔': ['galinha', 'frango', 'chicken'],
  '🐧': ['pinguim', 'penguin'],
  '🐦': ['pássaro', 'passaro', 'ave', 'bird'],
  '🦆': ['pato', 'duck'],
  '🦅': ['águia', 'aguia', 'eagle'],
  '🦉': ['coruja', 'owl'],
  '🦇': ['morcego', 'bat'],
  '🐺': ['lobo', 'wolf'],
  '🐗': ['javali', 'boar'],
  '🐴': ['cavalo', 'horse'],
  '🦄': ['unicórnio', 'unicornio'],
  '🐝': ['abelha', 'bee'],
  '🐞': ['joaninha', 'besouro'],
  '🦋': ['borboleta', 'butterfly'],
  '🐌': ['caracol', 'snail'],
  '🐛': ['lagarta', 'inseto'],
  '🕷️': ['aranha', 'spider'],
  '🦂': ['escorpião', 'escorpiao', 'scorpion'],
  '🐍': ['cobra', 'snake'],
  '🦎': ['lagarto', 'lizard'],
  '🦖': ['tiranossauro', 'dinossauro', 'dino'],
  '🦕': ['dinossauro', 'dino'],
  '🐙': ['polvo', 'octopus'],
  '🦑': ['lula'],
  '🦐': ['camarão', 'camarao'],
  '🦀': ['caranguejo', 'crab'],
  '🐠': ['peixe'],
  '🐬': ['golfinho', 'dolphin'],
  '🐳': ['baleia', 'whale'],
  '🦈': ['tubarão', 'tubarao', 'shark'],
  '🐊': ['jacaré', 'jacare', 'crocodilo'],
  '🦓': ['zebra'],
  '🦍': ['gorila'],
  '🐘': ['elefante', 'elephant'],
  '🦏': ['rinoceronte'],
  '🦒': ['girafa', 'giraffe'],
  '🦘': ['canguru', 'kangaroo'],
  '🐎': ['cavalo', 'horse'],
  '🐏': ['carneiro'],
  '🐑': ['ovelha', 'sheep'],
  '🦙': ['lhama', 'alpaca'],
  '🐐': ['cabra', 'bode'],
  '🦌': ['cervo', 'veado', 'deer'],
  '🐕': ['cachorro', 'cão', 'dog'],
  '🐈': ['gato', 'cat'],
  '🦜': ['papagaio', 'parrot', 'arara'],
  '🦩': ['flamingo'],
  '🦢': ['cisne', 'swan'],
  '🦃': ['peru', 'turkey'],
  '🦫': ['castor', 'beaver'],
  '🦥': ['bicho-preguiça', 'preguiça', 'sloth'],
  '🦦': ['lontra', 'otter'],
  '🦔': ['ouriço', 'ouriço', 'hedgehog'],
  '🐾': ['pata', 'pegada', 'paw'],
  '🌱': ['planta', 'broto', 'muda'],
  '🌿': ['erva', 'folha', 'ramo'],
  '🍀': ['trevo', 'sorte'],
  '🍂': ['folha', 'outono', 'folhas'],
  '🍁': ['folha', 'bordo', 'outono'],
  '🍄': ['cogumelo', 'mushroom'],
  '🌺': ['flor', 'hibisco'],
  '🌸': ['flor', 'cerejeira', 'sakura'],
  '🌼': ['flor', 'margarida'],
  '🌻': ['girassol', 'sunflower'],
  '🌳': ['árvore', 'arvore', 'tree'],
  '🌲': ['pinheiro', 'árvore', 'tree'],
  '🌵': ['cacto', 'cactus'],
  '🌾': ['arroz', 'trigo', 'planta'],
  '🍃': ['folha', 'vento'],
  '🌍': ['terra', 'planeta', 'globo'],
  '🌎': ['terra', 'planeta', 'globo'],
  '🌏': ['terra', 'planeta', 'globo'],
  '🌙': ['lua', 'noite', 'moon'],
  '⭐': ['estrela', 'star'],
  '🌟': ['estrela', 'brilho', 'star'],
  '✨': ['brilho', 'faísca', 'sparkle'],
  '⚡': ['raio', 'energia', 'relâmpago', 'eletricidade'],
  '☀️': ['sol', 'dia', 'sun'],
  '⛅': ['nuvem', 'tempo', 'sol'],
  '☁️': ['nuvem', 'cloud'],
  '🌈': ['arco-íris', 'arcoiris', 'rainbow'],
  '❄️': ['neve', 'gelo', 'snow'],
  '🔥': ['fogo', 'fogo', 'fire'],
  '💧': ['gota', 'água', 'agua', 'droplet'],
  '🌊': ['onda', 'mar', 'água', 'wave'],
  '😀': ['sorriso', 'feliz', 'happy'],
  '😄': ['sorriso', 'feliz', 'risada'],
  '😂': ['risada', 'chorar de rir', 'laugh', 'crying'],
  '🤣': ['risada', 'rolando de rir', 'laugh'],
  '😊': ['sorriso', 'feliz', 'happy'],
  '😍': ['apaixonado', 'amor', 'coração nos olhos'],
  '🥰': ['apaixonado', 'amor', 'carinho'],
  '😘': ['beijo', 'beijinho', 'kiss'],
  '😋': ['gostoso', 'comida', 'delicioso', 'yummy'],
  '😎': ['frio', 'descolado', 'óculos', 'cool'],
  '🤩': ['estrelado', 'impressionado', 'stars'],
  '🥳': ['festa', 'celebração', 'party'],
  '😏': ['sorriso malicioso', 'maldoso'],
  '😢': ['triste', 'choro', 'cry'],
  '😭': ['chorando', 'choro', 'sobbing'],
  '😡': ['raiva', 'bravo', 'angry'],
  '🤯': ['mente explodida', 'explosão', 'mind blown'],
  '🥺': ['pidão', 'olhos grandes', 'suplicando'],
  '😴': ['sono', 'dormir', 'sleep'],
  '🤤': ['saliva', 'baba', 'desejo'],
  '😵': ['tonto', 'tontura', 'dizzy'],
  '🤢': ['enjoado', 'náusea', 'vômito'],
  '🤮': ['vômito', 'vomitando'],
  '🤧': ['espirro', 'doente', 'sneeze'],
  '😷': ['máscara', 'doente', 'mask'],
  '🤒': ['doente', 'febre', 'termômetro'],
  '🤑': ['dinheiro', 'rica', 'money'],
  '🤠': ['chapéu', 'cowboy'],
  '👻': ['fantasma', 'ghost'],
  '💀': ['caveira', 'morte', 'skull'],
  '👽': ['alien', 'alienígena'],
  '🤖': ['robô', 'robot'],
  '🎃': ['abóbora', 'halloween'],
  '😺': ['gato', 'feliz'],
  '👋': ['tchau', 'oi', 'acenar', 'wave'],
  '👍': ['positivo', 'joinha', 'like', 'ok', 'thumbs up'],
  '👎': ['negativo', 'dislike', 'thumbs down'],
  '👏': ['aplausos', 'palmas', 'clap'],
  '🙌': ['comemorando', 'braços para cima'],
  '🙏': ['por favor', 'obrigado', 'rezando', 'thanks'],
  '💪': ['força', 'músculo', 'muscle'],
  '🧠': ['cérebro', 'mente', 'brain'],
  '👀': ['olhos', 'olhando', 'eyes'],
  '❤️': ['coração', 'amor', 'heart'],
  '🧡': ['coração', 'laranja'],
  '💛': ['coração', 'amarelo'],
  '💚': ['coração', 'verde'],
  '💙': ['coração', 'azul'],
  '💜': ['coração', 'roxo'],
  '🖤': ['coração', 'preto'],
  '💔': ['coração partido', 'amor', 'broken'],
  '💕': ['corações', 'amor'],
  '💞': ['corações', 'girando', 'amor'],
  '💖': ['coração', 'brilho', 'amor'],
  '💘': ['coração', 'seta', 'coração flechado'],
  '💋': ['beijo', 'batom', 'kiss'],
  '🍎': ['maçã', 'maca', 'apple'],
  '🍌': ['banana'],
  '🍇': ['uva', 'uvas'],
  '🍓': ['morango', 'strawberry'],
  '🍊': ['laranja', 'orange'],
  '🍋': ['limão', 'limao', 'lemon'],
  '🍉': ['melancia', 'watermelon'],
  '🍑': ['pêssego', 'pessego', 'peach'],
  '🍍': ['abacaxi', 'pineapple'],
  '🥑': ['abacate', 'avocado'],
  '🥕': ['cenoura', 'carrot'],
  '🌽': ['milho', 'corn'],
  '🍅': ['tomate', 'tomato'],
  '🥦': ['brócolis', 'brocolis'],
  '🍞': ['pão', 'pao', 'bread'],
  '🧀': ['queijo', 'cheese'],
  '🍳': ['ovo', 'frito', 'panela'],
  '🍔': ['hambúrguer', 'hamburger'],
  '🍟': ['batata frita', 'fries'],
  '🍕': ['pizza'],
  '🌭': ['cachorro-quente', 'hot dog'],
  '🌮': ['taco'],
  '🌯': ['burrito'],
  '🍝': ['macarrão', 'espaguete', 'spaghetti'],
  '🍜': ['sopa', 'ramen', 'lava'],
  '🍣': ['sushi'],
  '🍱': ['bentô', 'marmita', 'bento'],
  '🍤': ['camarão', 'frito'],
  '🍰': ['bolo', 'doce', 'cake'],
  '🎂': ['bolo', 'aniversário', 'birthday'],
  '🍦': ['sorvete', 'ice cream'],
  '🍩': ['rosquinha', 'donut'],
  '🍪': ['biscoito', 'cookie'],
  '🍫': ['chocolate', 'chocolate'],
  '🍬': ['bala', 'doce', 'candy'],
  '🍭': ['pirulito', 'lollipop'],
  '🍿': ['pipoca', 'popcorn'],
  '☕': ['café', 'cafe', 'coffee'],
  '🍵': ['chá', 'cha', 'chá verde', 'tea'],
  '🥤': ['refrigerante', 'bebida', 'soda'],
  '🍺': ['cerveja', 'beer'],
  '🍷': ['vinho', 'wine'],
  '🍸': ['drink', 'coquetel', 'cocktail'],
  '🥂': ['brinde', 'taças', 'toast'],
  '⚽': ['futebol', 'bola', 'soccer', 'football'],
  '🏀': ['basquete', 'basquetebol', 'basketball'],
  '🏈': ['futebol americano'],
  '⚾': ['beisebol', 'baseball'],
  '🎾': ['tênis', 'tenis', 'raquete', 'tennis'],
  '🏐': ['vôlei', 'volei', 'volleyball'],
  '🎱': ['sinuca', 'bilhar', 'billiard'],
  '🏓': ['pingue-pongue', 'tênis de mesa'],
  '🏸': ['badminton'],
  '🏹': ['arco', 'flecha', 'archery'],
  '🎣': ['pesca', 'pescaria', 'fishing'],
  '🥊': ['boxe', 'luva', 'boxing'],
  '🥋': ['artes marciais', 'judô', 'karatê'],
  '🎿': ['esqui', 'ski'],
  '🏆': ['troféu', 'trofeu', 'trophy', 'vitória'],
  '🥇': ['medalha', 'ouro', 'primeiro', 'gold'],
  '🥈': ['medalha', 'prata', 'segundo'],
  '🥉': ['medalha', 'bronze', 'terceiro'],
  '🏅': ['medalha', 'prêmio'],
  '🎨': ['arte', 'pintura', 'paleta', 'art'],
  '🎬': ['cinema', 'filme', 'claquete', 'movie'],
  '🎤': ['microfone', 'mic', 'cantar', 'microphone'],
  '🎧': ['fone', 'headphone', 'ouvir', 'música'],
  '🎼': ['partitura', 'música', 'notas'],
  '🎹': ['piano', 'teclado', 'música'],
  '🎸': ['violão', 'violao', 'guitarra', 'guitar'],
  '🎺': ['trompete', 'trumpet'],
  '🎻': ['violino', 'violin'],
  '🥁': ['bateria', 'tambor', 'drum'],
  '🎲': ['dado', 'dados', 'dice'],
  '🎯': ['alvo', 'dardo', 'alvo', 'target'],
  '🎳': ['boliche', 'bowling'],
  '🎮': ['videogame', 'game', 'jogo', 'controle'],
  '🎰': ['caça-níqueis', 'slots', 'cassino'],
  '🧩': ['quebra-cabeça', 'puzzle'],
  '🚗': ['carro', 'automóvel', 'car'],
  '🚕': ['táxi', 'taxi'],
  '🚌': ['ônibus', 'onibus', 'bus'],
  '🚓': ['polícia', 'policia', 'viatura'],
  '🚑': ['ambulância', 'ambulancia'],
  '🚒': ['bombeiro', 'caminhão de bombeiro'],
  '🚙': ['suv', 'van'],
  '🚲': ['bicicleta', 'bike', 'bicycle'],
  '🛵': ['moto', 'lambreta', 'scooter'],
  '🏍️': ['moto', 'motocicleta', 'motorcycle'],
  '🚀': ['foguete', 'foguetão', 'rocket', 'espaço'],
  '🛸': ['ovni', 'disco voador', 'ufo', 'espaço'],
  '🚁': ['helicóptero', 'helicoptero'],
  '✈️': ['avião', 'aviao', 'avion', 'voo', 'plane'],
  '⛵': ['vela', 'barco', 'veleiro'],
  '🚢': ['navio', 'barco', 'ship'],
  '🚉': ['estação', 'trem'],
  '🚄': ['trem', 'alta velocidade'],
  '🚇': ['metrô', 'metro', 'subway'],
  '🏰': ['castelo', 'castle'],
  '🗽': ['estátua da liberdade'],
  '🗼': ['torre', 'tóquio'],
  '🏟️': ['estádio', 'stadio'],
  '🎡': ['roda-gigante', 'roda gigante'],
  '🎢': ['montanha-russa', 'montanha russa', 'rollercoaster'],
  '🏖️': ['praia', 'guarda-sol', 'beach'],
  '🏝️': ['ilha', 'paraíso', 'island'],
  '🌋': ['vulcão', 'vulcao', 'volcano'],
  '⛰️': ['montanha', 'mountain'],
  '🗻': ['monte fuji'],
  '🏠': ['casa', 'lar', 'home'],
  '🏡': ['casa', 'quintal'],
  '🏢': ['prédio', 'escritório', 'empresa'],
  '🏥': ['hospital', 'médico'],
  '🏫': ['escola', 'colégio', 'school'],
  '⛪': ['igreja', 'church'],
  '🕌': ['mesquita', 'mosque'],
  '⌚': ['relógio', 'relogio', 'pulso', 'watch'],
  '📱': ['celular', 'telefone', 'smartphone', 'phone'],
  '📲': ['celular', 'receber chamada'],
  '💻': ['notebook', 'laptop', 'computador'],
  '🖥️': ['computador', 'monitor', 'desktop'],
  '⌨️': ['teclado', 'keyboard'],
  '🖨️': ['impressora', 'printer'],
  '🖱️': ['mouse'],
  '🕹️': ['joystick', 'controle', 'arcade'],
  '💾': ['disquete', 'salvar', 'save'],
  '💿': ['cd', 'disco'],
  '📷': ['câmera', 'foto', 'camera'],
  '📸': ['câmera', 'flash'],
  '📹': ['filmadora', 'vídeo', 'camera'],
  '🎥': ['filmadora', 'câmera de filme', 'vídeo'],
  '📞': ['telefone', 'telefone fixo'],
  '☎️': ['telefone', 'telefone fixo'],
  '📺': ['televisão', 'tv'],
  '📻': ['rádio', 'radio'],
  '⏰': ['despertador', 'relógio', 'alarme'],
  '⏳': ['ampulheta', 'tempo', 'hourglass'],
  '⌛': ['ampulheta', 'tempo'],
  '📡': ['antena', 'sinal', 'radar', 'satélite'],
  '🔋': ['bateria', 'battery'],
  '🔌': ['tomada', 'plugue', 'energia'],
  '💡': ['lâmpada', 'ideia', 'lampada', 'light'],
  '🔦': ['lanterna', 'flashlight'],
  '💰': ['dinheiro', 'sacola de dinheiro', 'money'],
  '💳': ['cartão', 'cartao', 'crédito', 'card'],
  '💎': ['diamante', 'joia', 'diamond'],
  '🔧': ['chave', 'ferramenta', 'ajuste'],
  '🔨': ['martelo', 'hammer'],
  '⚙️': ['engrenagem', 'configuração', 'gear'],
  '🧲': ['ímã', 'imã', 'magnet'],
  '🔪': ['faca', 'cutelo', 'knife'],
  '🛡️': ['escudo', 'proteção', 'shield'],
  '🔮': ['bola de cristal', 'magia', 'crystal'],
  '💊': ['pílula', 'comprimido', 'remédio', 'pill'],
  '💉': ['seringa', 'injeção', 'vacina', 'syringe'],
  '🧬': ['dna'],
  '🦠': ['vírus', 'bactéria', 'virus'],
  '📎': ['clipe', 'clip', 'paperclip'],
  '✂️': ['tesoura', 'cortar', 'scissors'],
  '🗑️': ['lixeira', 'lixo', 'excluir', 'trash'],
  '🔍': ['lupa', 'buscar', 'pesquisar', 'zoom', 'search'],
  '🔒': ['cadeado', 'trancado', 'seguro', 'lock'],
  '🔓': ['cadeado', 'aberto', 'destrancar'],
  '🔑': ['chave', 'key'],
  '🛠️': ['ferramentas', 'martelo', 'chave inglesa'],
  '📌': ['pino', 'alfinete', 'pin'],
  '📚': ['livros', 'livro', 'estudar', 'books'],
  '📖': ['livro', 'aberto', 'ler'],
  '📝': ['anotar', 'escrever', 'nota', 'note'],
  '✏️': ['lápis', 'lapis', 'escrever', 'pencil'],
  '🎁': ['presente', 'bônus', 'gift', 'brinde'],
  '🎈': ['balão', 'balao', 'festa', 'balloon'],
  '🎉': ['festa', 'celebração', 'confete', 'party'],
  '🎊': ['festa', 'confete', 'comemoração'],
  '📦': ['caixa', 'pacote', 'box', 'parcel'],
  '📬': ['carta', 'correio', 'envelope'],
  '✉️': ['carta', 'email', 'envelope', 'mail'],
  '💬': ['balão de conversa', 'chat', 'mensagem', 'chat bubble'],
  '💭': ['pensamento', 'balão', 'idea'],
  '📢': ['alto-falante', 'megafone', 'anúncio', 'announcement'],
  '🔔': ['sino', 'notificação', 'bell'],
  '✅': ['ok', 'verde', 'check', 'correto'],
  '❌': ['x', 'errado', 'não', 'cross', 'wrong'],
  '⭕': ['círculo', 'o', 'circle'],
  '💢': ['irritado', 'veias', 'raiva'],
  '♻️': ['reciclar', 'reciclagem', 'recycle'],
  '⚜️': ['flor de lis', 'fleur'],
  '🔞': ['adulto', '18', 'proibido'],
  '🚫': ['proibido', 'não pode', 'forbidden'],
  '♾️': ['infinito', 'infinity'],
  '➕': ['mais', 'somar', 'adicionar', 'plus'],
  '➖': ['menos', 'subtrair', 'minus'],
  '✖️': ['multiplicar', 'vezes', 'x'],
  '➗': ['dividir', 'divisão', 'division'],
  '❓': ['interrogação', 'dúvida', 'pergunta', 'question'],
  '❗': ['exclamação', 'atenção', 'important'],
  '⁉️': ['interrogação', 'exclamação', 'surpresa'],
  '💯': ['cem', '100', 'perfeito', '100%'],
  '🎵': ['nota', 'música', 'music'],
  '🎶': ['notas', 'música', 'música tocando'],
  '👑': ['coroa', 'rei', 'rainha', 'crown'],
  '🎩': ['cartola', 'chapeu', 'magia'],
  '🧢': ['boné', 'boné', 'cap'],
  '🎓': ['formado', 'faculdade', 'diploma', 'graduação'],
  '💍': ['anel', 'aliança', 'anel de noivado'],
  '🪕': ['banjo'],
  '🎷': ['saxofone', 'sax'],
  '🪗': ['acordeão', 'acordeon'],
  '🎙️': ['microfone', 'estúdio', 'podcast'],
  '🖼️': ['quadro', 'moldura', 'foto', 'picture'],
  '🪀': ['ioiô', 'iô iô', 'yo-yo'],
  '🪁': ['pipa', 'papagaio', 'kite'],
  '🛹': ['skate', 'skate'],
  '🛼': ['patins', 'roller'],
  '🏊': ['natação', 'nadar', 'swimming'],
  '🏄': ['surf', 'surfing'],
  '🚴': ['bicicleta', 'ciclismo', 'cycling'],
  '🧗': ['escalada', 'climbing'],
  '🧘': ['meditação', 'yoga', 'meditar'],
  '🕺': ['dança', 'dancar', 'dancing'],
  '💃': ['dança', 'dançando', 'dancing'],
  '👫': ['casal', 'amigos', 'dupla'],
  '👶': ['bebê', 'bebe', 'baby'],
  '👧': ['menina', 'criança', 'girl'],
  '👦': ['menino', 'criança', 'boy'],
  '👩': ['mulher', 'woman'],
  '👨': ['homem', 'man'],
  '👵': ['avó', 'idosa'],
  '👴': ['avô', 'idoso'],
  '👮': ['policial', 'polícia', 'guard'],
  '🕵️': ['detetive', 'investigador'],
  '👷': ['operário', 'trabalhador', 'construção'],
  '👸': ['princesa', 'princess'],
  '🤴': ['príncipe', 'principe', 'prince'],
  '🧙': ['mago', 'bruxo', 'wizard'],
  '🧚': ['fada', 'fairy'],
  '🧛': ['vampiro', 'vampire'],
  '🧟': ['zumbi', 'zombie'],
  '🥷': ['ninja'],
  '🦸': ['herói', 'heroi', 'super-herói', 'hero'],
  '🦹': ['vilão', 'vilao', 'vilain'],
  '💂': ['guarda', 'soldado'],
  '🤰': ['grávida', 'gravida', 'gestante'],
  '🤱': ['amamentar', 'mãe'],
  '✌️': ['paz', 'v', 'dois', 'peace'],
  '🤞': ['torcer', 'dedos cruzados', 'good luck'],
  '🤟': ['eu te amo', 'rock'],
  '🤙': ['call me', 'liga'],
  '👌': ['ok', 'perfeito', 'ok'],
  '🤌': ['pinça', 'italiano'],
  '🤏': ['pouquinho', 'pouco', 'pinch'],
  '✋': ['mão', 'palma', 'stop', 'hand'],
  '👊': ['soco', 'punho', 'fist', 'bump'],
  '✊': ['punho', 'levantado', 'força', 'fist'],
  '👐': ['mãos abertas', 'open hands'],
  '🤝': ['aperto de mão', 'acordo', 'handshake'],
  '🦴': ['osso', 'bone'],
  '🦷': ['dente', 'tooth'],
  '👅': ['língua', 'lingua', 'tongue'],
  '👄': ['boca', 'lábios', 'mouth'],
  '👃': ['nariz', 'nose'],
  '👂': ['orelha', 'ouvido', 'ear'],
  '👁️': ['olho', 'eye'],
  '💄': ['batom', 'maquiagem', 'lipstick'],
  '👓': ['óculos', 'oculos', 'glasses'],
  '🕶️': ['óculos', 'escuros', 'sunglasses'],
  '👔': ['gravata', 'camisa', 'terni'],
  '👕': ['camiseta', 'camiseta', 'tshirt'],
  '👖': ['calça', 'calca', 'jeans'],
  '👗': ['vestido', 'dress'],
  '👙': ['biquíni', 'bikini'],
  '👞': ['sapato', 'shoe'],
  '👟': ['tênis', 'tenis', 'sneaker'],
  '🥾': ['bota', 'boot'],
  '👛': ['carteira', 'bolsa', 'wallet'],
  '👜': ['bolsa', 'purse'],
  '🎒': ['mochila', 'backpack'],
  '🕳️': ['buraco', 'hole'],
  '🌡️': ['termômetro', 'temperatura', 'thermometer'],
  '🧯': ['extintor', 'incêndio', 'extinguisher'],
  '🪣': ['balde', 'bucket'],
  '🧹': ['vassoura', 'limpeza'],
  '🧺': ['cesto', 'cesta', 'basket'],
  '🧻': ['papel', 'rolo', 'toalha'],
  '🗝️': ['chave', 'key'],
  '🔭': ['telescópio', 'telescopio'],
  '🔬': ['microscópio', 'microscopio', 'ciência'],
  '⚗️': ['alquimia', 'química', 'destilação'],
  '🧪': ['tubo de ensaio', 'laboratório', 'ciência', 'teste'],
  '🧫': ['placa de petri', 'bactéria', 'ciência'],
  '🩺': ['estetoscópio', 'médico', 'doctor'],
  '🩹': ['curativo', 'band-aid'],
  '🧰': ['caixa de ferramentas', 'tools'],
  '🔩': ['parafuso', 'porca', 'bolt'],
  '🪛': ['chave de fenda', 'screwdriver'],
  '🪚': ['serra', 'saw'],
  '🪓': ['machado', 'axe'],
  '🗡️': ['adaga', 'faca', 'dagger'],
  '⚔️': ['espadas', 'cruzadas', 'swords'],
  '🛏️': ['cama', 'dormir', 'bed'],
  '🛋️': ['sofá', 'sofa'],
  '🚪': ['porta', 'door'],
  '🪟': ['janela', 'window'],
  '🚽': ['banheiro', 'vaso sanitário'],
  '🛁': ['banheira', 'banho'],
  '🚿': ['chuveiro', 'banho'],
  '🧴': ['loção', 'frasco', 'creme'],
  '🧼': ['sabonete', 'sabão', 'soap'],
  '🪒': ['lâmina', 'barbeador', 'razor'],
  '🧽': ['esponja', 'sponge'],
  '🪥': ['escova de dentes', 'toothbrush'],
  '🧨': ['bomba', 'fogos', 'dynamite'],
  '💣': ['bomba', 'bomb'],
  '🧿': ['olho grego', 'nazar'],
  '🪄': ['varinha', 'mágica', 'wizard'],
  '📿': ['terço', 'colar', 'contas'],
  '🪙': ['moeda', 'coin'],
  '🧾': ['recibo', 'cupom', 'receipt'],
  '📜': ['pergaminho', 'documento', 'scroll'],
  '📃': ['documento', 'papel', 'page'],
  '📑': ['marcador', 'favoritos', 'bookmark'],
  '🔖': ['marcador', 'favorito', 'bookmark'],
  '🏷️': ['etiqueta', 'tag', 'preço'],
  '💶': ['euro', 'dinheiro'],
  '💷': ['libra', 'dinheiro'],
  '💴': ['iene', 'dinheiro'],
  '💵': ['dólar', 'dinheiro', 'cédula'],
  '💸': ['dinheiro', 'voando', 'gastar'],
  '🪪': ['identidade', 'carteira', 'documento'],
  '🛒': ['carrinho', 'compras', 'cart'],
  '🛍️': ['sacolas', 'compras'],
  '🎀': ['laço', 'fita', 'bow'],
  '🧵': ['linha', 'costura', 'thread'],
  '🧶': ['lã', 'fio', 'tricô', 'yarn'],
  '🧷': ['alfinete', 'broche', 'safety pin'],
  '📏': ['régua', 'regua', 'ruler'],
  '📐': ['esquadro', 'régua', 'triângulo'],
  '🧮': ['ábaco', 'abaco'],
  '🖲️': ['trackball'],
  '🗂️': ['pastas', 'arquivo', 'organizar'],
  '🗃️': ['caixa de arquivo'],
  '🗄️': ['arquivo', 'gaveta'],
  '🗳️': ['urna', 'voto', 'votar'],
  '🗓️': ['calendário', 'agenda'],
  '📅': ['calendário', 'data'],
  '📆': ['calendário', 'agenda'],
  '📈': ['gráfico', 'subindo', 'crescimento'],
  '📉': ['gráfico', 'caindo', 'queda'],
  '📊': ['gráfico', 'barras'],
  '🗜️': ['grampo', 'braçadeira'],
  '🧱': ['tijolo', 'parede', 'brick'],
  '🧊': ['gelo', 'ice'],
  '🧭': ['bússola', 'bussola', 'compass'],
  '📟': ['pager', 'bip'],
  '📠': ['fax'],
  '📤': ['enviar', 'outbox'],
  '📥': ['receber', 'inbox'],
  '📨': ['envelope', 'enviado'],
  '📩': ['envelope', 'seta', 'enviado'],
  '💌': ['carta de amor', 'amor'],
  '📧': ['email', 'correio'],
  '📭': ['caixa', 'vazia'],
  '📮': ['caixa de correio'],
  '🗿': ['moai', 'estátua', 'mohai'],
  '⛲': ['fonte', 'água'],
  '⛱️': ['guarda-sol', 'praia', 'umbrella'],
  '🗺️': ['mapa', 'map'],
  '🏕️': ['acampamento', 'camping'],
  '🏞️': ['parque', 'paisagem', 'natureza'],
  '🌄': ['nascer do sol', 'montanha'],
  '🌅': ['nascer do sol', 'amanhecer'],
  '🌇': ['pôr do sol', 'cidade'],
  '🌆': ['cidade', 'entardecer'],
  '🏙️': ['cidade', 'city'],
  '🌃': ['noite', 'cidade', 'estrelas'],
  '🌌': ['galáxia', 'via láctea', 'espaço'],
  '🌠': ['estrela cadente'],
  '🌉': ['ponte', 'noite'],
  '🌁': ['névoa', 'nevoeiro'],
  '🎇': ['fogos', 'faíscas', 'fireworks'],
  '🎆': ['fogos de artifício', 'fireworks'],
  '🎑': ['lua', 'cenário'],
  '🗾': ['japão', 'mapa'],
  '🚧': ['obras', 'construção', 'barreira'],
  '🚦': ['semáforo', 'sinal'],
  '🚥': ['semáforo', 'horizontal'],
  '⛽': ['posto', 'gasolina', 'combustível'],
  '🛑': ['pare', 'stop', 'vermelho'],
  '🔴': ['vermelho', 'círculo', 'red'],
  '🟠': ['laranja', 'círculo', 'orange'],
  '🟡': ['amarelo', 'círculo', 'yellow'],
  '🟢': ['verde', 'círculo', 'green'],
  '🔵': ['azul', 'círculo', 'blue'],
  '🟣': ['roxo', 'círculo', 'purple'],
  '⚫': ['preto', 'círculo', 'black'],
  '⚪': ['branco', 'círculo', 'white'],
  '🟤': ['marrom', 'círculo', 'brown'],
  '🫀': ['coração', 'órgão', 'heart'],
  '🫁': ['pulmão', 'lungs'],
  '🦻': ['ouvido', 'aparelho auditivo'],
  '🦿': ['perna mecânica', 'prótese'],
  '🦾': ['braço mecânico', 'robô'],
  '🦵': ['perna', 'leg'],
  '🦶': ['pé', 'pe', 'foot'],
  '👣': ['pegadas', 'passos'],
  '💅': ['unha', 'esmalte', 'nail'],
  '🫦': ['mordendo', 'lábios'],
  '🫄': ['grávido'],
  '🫃': ['grávido'],
  '👨‍👩‍👧‍👦': ['família', 'family'],
  '👪': ['família', 'family'],
  '👨‍💻': ['programador', 'dev', 'computador'],
  '👩‍💻': ['programadora', 'dev', 'computador'],
  '👨‍🎓': ['estudante', 'formado'],
  '👩‍🎓': ['estudante', 'formada'],
  '🧑‍🚀': ['astronauta', 'espaço'],
  '👨‍🚀': ['astronauta'],
  '🧑‍🏫': ['professor', 'professora', 'teacher'],
  '👨‍⚕️': ['médico', 'medico', 'doctor'],
  '👩‍⚕️': ['médica', 'medica', 'doctor'],
  '🧑‍🍳': ['cozinheiro', 'chef'],
  '👨‍🍳': ['cozinheiro', 'chef'],
  '🧑‍🔧': ['mecânico', 'técnico'],
  '🧑‍🎨': ['artista', 'pintor'],
  '🧑‍🚒': ['bombeiro'],
  '🧑‍✈️': ['piloto'],
  '👮‍♂️': ['policial'],
  '👮‍♀️': ['policial'],

};

function normalize(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

export interface EmojiSearchResult {
  label: string;
  emojis: string[];
}

/** Filtra os emojis por categoria + palavras-chave. Vazio retorna tudo. */
export function searchEmojis(query: string): EmojiSearchResult[] {
  const raw = query.trim();
  if (!raw) {
    return EMOJI_CATEGORIES.map((c) => ({ label: c.label, emojis: c.emojis }));
  }
  const q = normalize(raw);
  return EMOJI_CATEGORIES.map((cat) => {
    const catMatches = normalize(cat.label).includes(q);
    const emojis = cat.emojis.filter((e) => {
      if (catMatches) return true;
      if (normalize(e).includes(q)) return true;
      const kws = EMOJI_KEYWORDS[e] ?? [];
      return kws.some((k) => normalize(k).includes(q));
    });
    return { label: cat.label, emojis };
  }).filter((c) => c.emojis.length > 0);
} 
